### ISSUE TITLE
Not possible to use PDN Type 3: malformed IE

### ISSUE THREAD

**Issue by dkalashnik** [wmnsk/go-gtp#113]
The current implementation of the IP address selection does not support the PDNType == 3. It always leads to the malformed IE error:
https://github.com/wmnsk/go-gtp/blob/master/gtpv2/ie/ip-addr.go#L72-L87

**Comment by wmnsk** [comment]
Fixed in #114. Thank you for reporting.
FYI, better replacing `master` with the exact commit hash in URL when pasting, as the line number may change.
