### ISSUE TITLE
Testing with NextEPC

### ISSUE THREAD

**Issue by syauqisabili** [wmnsk/go-gtp#149]
Hello, has anyone tried this tester with NextEPC?
I've tried but still doesn't work.

**Comment by wmnsk** [comment]
Do you have specific information such as logs from both sides? Otherwise I can't even try to help you.

**Comment by syauqisabili** [comment]
sorry and thank you for your reply,

this error appears when i run enb
![image](https://user-images.githubusercontent.com/38504766/108939300-12e9b980-7684-11eb-87e0-2c0c30f666a0.png)

and this is my capture.
[gwtester.zip](https://github.com/wmnsk/go-gtp/files/6032994/gwtester.zip)

**Comment by wmnsk** [comment]
Could you tell me how your setup is? Do you use MME of gw-tester?

**Comment by wmnsk** [comment]
Let me know if you need further help.
