### ISSUE TITLE
envoy 0.9.9 dependency introduced by grpc v1.36.0

### ISSUE THREAD

**Issue by uri200** [wmnsk/go-gtp#155]
Hey @wmnsk,

It looks like `google.golang.org/grpc v1.36.0` introduced a dependency on `github.com/envoyproxy/go-control-plane@v0.9.9-0.20201210154907-fd9021fe5dad` (see link below)

That is not a stable version and it is giving us conflicts between modules, preventing us to move to `go-gtp v0.7.16`

Is it possible to revert this change for now?

https://github.com/wmnsk/go-gtp/commit/70c7750ac2d77490ce4981b5091e5c26a8481270

**Comment by wmnsk** [comment]
Reverted and tagged `v0.7.17`. It'd be great if you could tell me when the problem is solved and we can update that package.

**Comment by uri200** [comment]
Thanks! I will let you know.

**Comment by wmnsk** [comment]
👍

**Comment by wmnsk** [comment]
okay, will do. thanks for letting me know 👍
