### ISSUE TITLE
OffendingIE in Cause()  type

### ISSUE THREAD

**Issue by uri200** [wmnsk/go-gtp#165]
Hi,

Sorry but we are very active lately on gtp side, that's why you see an increase of questions from Magma 🙂

When there is a missing IE, the server normally responds with an error cause `CauseMandatoryIEIncorrect` or `CauseMandatoryIEMissing`. Right now per what I understand, the `Cause` type does not implement any function to parse out from the message the OffendingIE type. 

Is that correct? Or maybe I missed something? 

![image](https://user-images.githubusercontent.com/16157139/113644078-b7262f00-9638-11eb-8e82-fa911db4d30f.png)

**Comment by wmnsk** [comment]
NP. Rather, I appreciate helping improve this package :smiley: 
Does #166 satisfy what you pointed out?

**Comment by uri200** [comment]
Nice!! 

Yes that will work
I will keep this example for future reference in case we want to implement other IEs!

**Comment by wmnsk** [comment]
Good! Please be sure that it doesn't check what type of Cause it actually has, for the flexibility. I'll tag again later.

**Comment by uri200** [comment]
Thanks! what we really need is, in case of your example, the `76` which corresponds to `AccessPointName`
