### ISSUE TITLE
Delete bearer from SGW/PGW

### ISSUE THREAD

**Issue by northmirko** [wmnsk/go-gtp#171]
Hi, I always get error from MME (S11), when trying to delete bearer from remote side (SGW/PGW).

`failed to validate Delete Bearer Request: got invalid TEID: 0xb73f837e`
 
I can provide further logs.

**Comment by wmnsk** [comment]
Sounds strange. Could you share the details of the setup and the logs/pcaps?

**Comment by northmirko** [comment]
Ok, things are trivial at the end. If Delete Bearer is sent from SGW, in current example for MME, you didn't add handler for msgType: DeleteBearer**Request** on MME side. So, not a big deal. I will close this issue if you don't mind.

**Comment by northmirko** [comment]
I have found true cause, SGW is sending DeleteBearerRequest with **UDP source port different** than allocated to GTPC. I think this is not according to specs.
