### ISSUE TITLE
cannot create GTP device; Operation not supported

### ISSUE THREAD

**Issue by dramasamy** [wmnsk/go-gtp#172]
Uname info: Linux 05911578bd58 4.18.0-193.1.2.el8_2.x86_64 #1 SMP Thu May 7 16:37:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[root@05911578bd58 libgtp5gnl]# ip netns exec ue1 gtp-link add ue1
cannot create GTP device
: Operation not supported

Strace:
-------
arch_prctl(ARCH_SET_FS, 0x7f8bb4926740) = 0
mprotect(0x7f8bb42f8000, 16384, PROT_READ) = 0
mprotect(0x7f8bb4506000, 4096, PROT_READ) = 0
mprotect(0x7f8bb470b000, 4096, PROT_READ) = 0
mprotect(0x601000, 4096, PROT_READ)     = 0
mprotect(0x7f8bb4935000, 4096, PROT_READ) = 0
munmap(0x7f8bb4929000, 39001)           = 0
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 3
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 4
bind(3, {sa_family=AF_INET, sin_port=htons(3386), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
bind(4, {sa_family=AF_INET, sin_port=htons(2152), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
brk(NULL)                               = 0xf69000
brk(0xf8a000)                           = 0xf8a000
brk(NULL)                               = 0xf8a000
socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE) = 5
bind(5, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 0
getsockname(5, {sa_family=AF_NETLINK, nl_pid=133, nl_groups=00000000}, [12]) = 0
sendto(5, {{len=80, type=0x10 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x600, seq=1619647437, pid=0}, "\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x07\x00\x03\x00\x75\x65\x31\x00\x28\x00\x12\x80\x07\x00\x01\x00"...}, 80, 0, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, 12) = 80
recvmsg(5, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=100, type=NLMSG_ERROR, flags=0, seq=1619647437, pid=133}, {error=-EOPNOTSUPP, msg={{len=80, type=0x10 /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK|0x600, seq=1619647437, pid=0}, "\x02\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x07\x00\x03\x00\x75\x65\x31\x00\x28\x00\x12\x80\x07\x00\x01\x00"...}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 100

**Comment by wmnsk** [comment]
It doesn’t seem you’re working with this project.

**Comment by dramasamy** [comment]
Oops, wrong project. 

https://osmocom.org/projects/openggsn/wiki/Kernel_GTP
