### ISSUE TITLE
BearerTFT implementation

### ISSUE THREAD

**Issue by uri200** [wmnsk/go-gtp#180]
Hey @wmnsk,

Is there any plans to implement `Bearer Level Traffic Flow Template (Berare TFT)` any time soon.

Thanks!

**Comment by wmnsk** [comment]
It's not planned, but done in #181 and added a new tag. Please check if it works carefully, as it's fairly complicated. General review for the added code is also appreciated :)

**Comment by uri200** [comment]
Awesome!!! 
Will review and also test it out with our setup!

Thanks!

**Comment by wmnsk** [comment]
@uri200 Please note that the Bearer TFT implementation will be changed a little in the latest release: v0.7.25 / PR #182 (As I've seen it's not yet used in magma perhaps?).

**Comment by uri200** [comment]
> @uri200 Please note that the Bearer TFT implementation will be changed a little in the latest release: v0.7.25 / PR #182 (As I've seen it's not yet used in magma perhaps?).

Hey @wmnsk, I am still working on a PR for using it. BTW, I have tested it with one of our test setups and it did work.

But go ahead and do your changes. I will rebase mine and modify my PR accordingly.

Thanks for letting us know!

**Comment by wmnsk** [comment]
It’s merged. From BearerTFT point of view, it’s just a change of the type name: `BearerTFTFields` => `TrafficFlowTemplate`. Hope it won’t require much work.

Since it’s working so far I’m closing this issue for now. Let me know if anything’s wrong by reopening or creating a new issue 👍
