### ISSUE TITLE
GTP version 1 with extension header

### ISSUE THREAD

**Issue by baleeiro17** [wmnsk/go-gtp#185]
Hi @wmnsk , thank you for amazing project. I need to test UPF with GTP version 1 with extension header. I was wondering if your project has any kind of facilities to do that. I tried to change message.header struct without sucess.  Any help about this ? I attach an example of extension header that I tried to reproduce in go-gtp.

[extension-header.zip](https://github.com/wmnsk/go-gtp/files/6696589/extension-header.zip)

**Comment by wmnsk** [comment]
We currently don’t have it supported, but it’s in my todo list that I will work on some day I’m motivated enough 😉

**Comment by wmnsk** [comment]
@baleeiro17 We’ve done the implementation of Extension Header at v0.7.28. Hope you are still up there and our work helps.

Doc: https://github.com/wmnsk/go-gtp/blob/master/gtpv1/README.md#handling-extension-headers
