### ISSUE TITLE
5G GTP-U Load Generator

### ISSUE THREAD

**Issue by infinitydon** [wmnsk/go-gtp#187]
Hi,

Please I will like to ask if an example for generating GTPU load test towards a UPF can be made.

I was able to get something from the following repo https://gitlab.eurecom.fr/kharade/gtp-traffic-generator but unfortunately I could not build it (I have tried severally to contact the repo owner and the OAI forum but I did not get any response).

Currently I don't have in-depth Golang skills but I think this is something that might be of value, I will appreciate if someone can assist in this regard.

**Comment by wmnsk** [comment]
If what you want is just generating GTPv1-encapsulated traffic, you don't need this project - on a Linux machine, create tunnel(s) with [gtp5g](https://github.com/PrinzOwO/gtp5g) and [libgtp5gnl](https://github.com/PrinzOwO/libgtp5gnl) (or directly via netlink), write some routes/rules on your machine, and put some loads toward that. I think [this slide](https://www.slideshare.net/kentaroebisawa/using-gtp-on-linux-with-libgtpnl) help you to some extent though it's not for 5G. Please don't ask me further on how exactly to make it work, as it's not related to this project.

If you need to handle GTPv2-C(and perhaps PFCP) as well, please learn Go and build your own tool. This is a library to help developers write such codes, not standalone software. Of course, I'm here to help you with specific questions during your work ;)

**Comment by wmnsk** [comment]
Ah, or simulators like [UERANSIM](https://github.com/aligungr/UERANSIM) may suffice.

**Comment by infinitydon** [comment]
Thanks @wmnsk -- I understand your perspective, I will also check the recommended links. I am already using UERANSIM as a basic simulator, I just wanted to focus strictly on load testing the 5G userplane function.
