### ISSUE TITLE
Delete Bearer Request - Linked EPS Bearer

### ISSUE THREAD

**Issue by uri200** [wmnsk/go-gtp#188]
Hey @wmnsk 

Checking the code where Delete Bearer Request I can see there is no difference between Linked EPS Bearer ID and EPS Bearer ID. Per what I understand per 3GPP 29.274 specs, we can have either or and both have a different IE type value. 

Is this intentional? How can we differentiate between them in case it were needed?

![image](https://user-images.githubusercontent.com/16157139/127891777-8efa1f93-a3f4-4822-8663-9b2743e543c5.png)

(page 123)
https://www.etsi.org/deliver/etsi_ts/129200_129299/129274/16.05.00_60/ts_129274v160500p.pdf

**Comment by wmnsk** [comment]
The instance id should do that work. Use `.SetInstance(1)` for EPS Bearer ID (otherwise it’s regarded as Linked EBI).

**Comment by wmnsk** [comment]
Did it go well woth uour code? Let me know if you need further help.
