### ISSUE TITLE
Add parser of extension header with AddHandler

### ISSUE THREAD

**Issue by yt8956gh** [wmnsk/go-gtp#189]
Hi, I'm in the free5gc team and coding for free5GC/N3IWF.
We want to support the extension header in gtp and had seen the related discussion in [issue #185](https://github.com/wmnsk/go-gtp/issues/185). It seems to be improbable to make go-gtp support the field recently. 

Therefore, we try to add a new T-PDU parser to support the extension header by AddHandler of UPlaneConn. 

However, the handler function is defined out of gtpv1. It's impossible to access some critical parameters (e.g. tpduSet, tpduCh for sending T-PDU) due to the lack of related public methods. Is there any solution for them? Thank you in advance !!

**Comment by wmnsk** [comment]
Good news is that I started working on implementing the Extension Header. What’s bad is it’ll take some time to finish (hopefully this weekend?).

**Comment by wmnsk** [comment]
Oh I just saw your PR, what a coincidence! 😁

**Comment by yt8956gh** [comment]
Hi, @wmnsk 
I just saw your comment pop out when I key this comment.
Hope this PR can help !!

**Comment by wmnsk** [comment]
As talked in your PR, I’ve modified the implementation and tagged v0.7.28. Docs here: https://github.com/wmnsk/go-gtp/blob/master/gtpv1/README.md#handling-extension-headers
