### ISSUE TITLE
Multiple bearer context  on one request

### ISSUE THREAD

**Issue by uri200** [wmnsk/go-gtp#192]
Hey @wmnsk 

Maybe I have missed it in the code, but we are trying to implement `Create Bearer Request` with multiple dedicated bearers on one request. Per [3gpp S 29.274](https://www.etsi.org/deliver/etsi_ts/129200_129299/129274/09.08.00_60/ts_129274v090800p.pdf) Create Bearer Request can have several `Bearer Context` IEs on the request. 

![image](https://user-images.githubusercontent.com/16157139/134251277-94a33813-5e24-4a5e-ac5a-3f2162d9073c.png)

I have created a test Create Bearer Request with two dedicated bearers like this below

```
	pgwFTEIDu := ie.NewFullyQualifiedTEID(
		gtpv2.IFTypeS5S8PGWGTPU, req.BearerContext.Pgw_u_teid, req.BearerContext.Pgw_u_ip, "").WithInstance(1)

	pgwFTEIDu_2 := ie.NewFullyQualifiedTEID(
		gtpv2.IFTypeS5S8PGWGTPU, req.BearerContext.Pgw_u_teid+1, req.BearerContext.Pgw_u_ip, "").WithInstance(1)


	ies := []*ie.IE{
		ie.NewEPSBearerID(session.GetDefaultBearer().EBI),
		ie.NewBearerContext(
			ie.NewEPSBearerID(req.BearerContext.DedicatedBearereID),
			buildNewBearerTFTCreateNewTFT(req),
			ie.NewBearerQoS(1, 0, 1, req.QosQCI, 0x1111111111, 0x2222222222, 0x1111111111, 0x2222222222),
			ie.NewChargingID(req.ChargingID),
			pgwFTEIDu,
		),
		ie.NewBearerContext(
			ie.NewEPSBearerID(req.BearerContext.DedicatedBearereID+1),
			buildNewBearerTFTCreateNewTFT(req),
			ie.NewBearerQoS(2, 2, 2, req.QosQCI, 0xFFFFFFFFFF, 0xAAAAAAAAAA, 0x1111111123, 0x2222222456),
			ie.NewChargingID(req.ChargingID+1),
			pgwFTEIDu_2,
		),
	}
```

but when we send that message, we are not sure how we can parse the two bearers once we received the GTP message on the other end. We normally use `brCtxIE := cbReqGtp.BearerContexts` , but this seems to extract only one context. 

Am I am missing any function that may be extracting a slice of context perhaps?

**Comment by uri200** [comment]
It looks like implementation of Create Bearer Request is only accepting one single bearer, instead of a slice [here](https://github.com/uri200/go-gtp/blob/994cf0b5c35fb56b68b5531bacd4c35a8dcaccb3/gtpv2/message/create-bearer-req.go#L56-L56) if I am not wrong?

**Comment by wmnsk** [comment]
Thanks for reporting @uri200! The code you pointed out seems to be the right place to fix according to the spec and the fix would be simple, but let me examine the side effects.

**Comment by wmnsk** [comment]
@uri200 
Other than this, there seems to be many more to be fixed (#193). I'll fix them together soon. Heads up: it affects some other messages you might be using, including Create Session Request/Response etc.

**Comment by uri200** [comment]
That is fine @wmnsk, we will refactor our code to handle multiple IEs of the same type once your changes are merged.
Thanks!!

**Comment by wmnsk** [comment]
@uri200 Check out `v0.8.0` and let me know if anything doesn't work well!

**Comment by uri200** [comment]
Thanks, we included now the support just for delete bearer

The rest are hardcoded to index [0] but we will move them progressively.

Thanks @wmnsk  for quick turnaround!
