### ISSUE TITLE
Informative question regarding GTPv1-C

### ISSUE THREAD

**Issue by northmirko** [wmnsk/go-gtp#196]
Hi,

GTPv1-C connection object (Conn) is not implemented.
I suppose logic is analog  with GTPv2-C, correct me if I am wrong.
Did you have lack of time, or there is something else that stops you implementing GTPv1-C networking part ?
Is there any particular issue we need to be aware of, if we want to implement GTPv1-C Conn on our own (and possibly contribute to your code foundation at the end) ?

Thank you.

**Comment by wmnsk** [comment]
Hi!
I’m leaving it just because it’s ~very cumbersome~ time-consuming while I haven’t seen much demands for that. And yes, the implementation would be quite similar to that of GTPv2, and as far as I see there are no known issues or such.

**Comment by northmirko** [comment]
I have managed to make simple code adjustments for SGSN, and write test unit.
Seamless code integration, thank you for that possibility.
"Osmocom" GGSN was used as counterpart.
I am willing to share code, of course, but still need to improve the new codebase.

**Comment by wmnsk** [comment]
@northmirko Sounds great! I'd appreciate your contribution of course. Let me know if I can be of your help complete your implementation.

**Comment by northmirko** [comment]
I made an analogous example for SGSN, like you did for MME, in example directory. Works just fine with OSMOCOM SGSN. Necessary handlers added, so now GGSN can initiate DELETE PDP REQUEST. Also, sequence number must be handled in another way, when some kind of PDP **request** is initiated by GGSN.

![image](https://user-images.githubusercontent.com/2362694/147746973-6c1ebdf0-1041-492f-8412-07408a984295.png)

But, u-conn gtpv1 can't be made.
I get **operation not supported** in tunnel_linux.go.
```
	if err := netlink.LinkAdd(u.KernelGTP.Link); err != nil {
		_ = f.Close()
		return fmt.Errorf("failed to add device %s: %w", u.KernelGTP.Link.Name, err)
	}
```
I suspect current kernel version is not supported with **netlink** , maybe. 
**libgtpnl** is installed successfully. 
Kernel version:
`Linux ubuntu-hirsute 5.11.0-41-generic #45-Ubuntu SMP Fri Nov 5 11:37:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by northmirko** [comment]
I have too much "generic" version of kernel, no module gtp.ko. Netlink works after installing this extra module.
