### ISSUE TITLE
S1MME protocol buffers generation

### ISSUE THREAD

**Issue by northmirko** [wmnsk/go-gtp#197]
Hi, I want to extend the following code in **s1mme.proto** :
```
message AttachResponse {
    Cause cause = 1; // result
    string sgw_addr = 2;
    uint32 o_tei = 3;
    **string user_ip = 4;**////I want to return this from IE END-USER-ADDRESS
}
```

But cant generate s1mme.pb.go. 
What command do you use to generate this file?
I tried (after some basic research on protocol buffers)
**protoc -I=. --go_out=s1mme s1mme/s1mme.proto**

But **s1mme.AttacherClient, s1mme.AttacherServer** are not generated.
I don't know how to use Protocol Buffers, at the moment. I haven't got experience from that API yet.
Hoping you can help with this small extension @wmnsk ?

**Comment by wmnsk** [comment]
Something might have changed... Adding `option go_package = "./";` in s1mme.proto made it compiled successfully at least (not tested as a whole though).

**Comment by northmirko** [comment]
...one year after....
I don't know what happened last time, with basic manipulation of **protoc** and **protoc-gen-go**
`protoc --proto_path=. --go_out=. --go_opt=paths=source_relative s1mme.proto` code is changed.

![image](https://user-images.githubusercontent.com/2362694/219654230-cadef033-4d3a-4e03-9a74-b7a0cc0d6ea2.png)

![image](https://user-images.githubusercontent.com/2362694/219654419-01baeedb-dfab-4eec-b25d-2b04a36e904e.png)
