### ISSUE TITLE
About the GTP-U Header Length Checking

### ISSUE THREAD

**Issue by JinghaoZhao** [wmnsk/go-gtp#207]
https://github.com/wmnsk/go-gtp/blob/c6c616cb34d52a5c735f2b2f193c8dcc0deda3f6/gtpv1/message/header.go#L124

First thanks for the great efforts of developing and sharing the go-gtp! We are working on an extension of the current gtpv1 to support the End Marker. After the testing we find that the current header checking (the code above) set the limits to 11. However, the 3GPP 29.281 mentions that "The GTP-U header is a variable length header whose minimum length is 8 bytes." Also, the End Marker does not have the sequence number, n-pdu number, or the extension header, thus only have 8 bytes and will fail on this checking. 

<img width="699" alt="image" src="https://user-images.githubusercontent.com/14849026/177420989-6fcac38a-f292-4610-abac-41319aa291b6.png">

I'm wondering if this checking should be 8 rather than 11, or my understanding is somehow incorrect. Thanks!

**Comment by wmnsk** [comment]
Thank you for reporting! #209 should fix this. Please try with v0.8.3.
