### ISSUE TITLE
Extension Header Type List length field is one byte

### ISSUE THREAD

**Issue by oicnysa** [wmnsk/go-gtp#213]
Hello,
I've found an issue in Extension Header Type List length field size. As you have generic ie structure, which has two byte length size, the same is applied to Extension Header Type List length field size, which has one byte length field size, which leads to error in this information element. Thanks.

**Comment by wmnsk** [comment]
Ahah what a trap! 3GPP really likes to annoy us with such things :)
Thanks for reporting. I'll check and fix it hopefully in a few days.

**Comment by oicnysa** [comment]
I've been thinking about how to fix it quickly, but couldn't come with quick solution. Not so much knowledge about go-gtp, but seems you have length field size for all ies 2 bytes.

**Comment by wmnsk** [comment]
Yeah it’d be some unusual work. I have some ideas on how to make it work but didn’t have time to try. Maybe next week I can do.

**Comment by wmnsk** [comment]
@oicnysa I've added exceptions for Extension Header Type List in parsing/marshaling common IE structure at b24e7e8033b7306e9edb91a61a86923c137098c4. Though the length field of the structure is still of type `uint16`, it should be parsed/marshaled as the specification defines.

**Comment by oicnysa** [comment]
Thank you very much!
