### ISSUE TITLE
S1AP on top of TCP? 

### ISSUE THREAD

**Issue by dchard** [wmnsk/go-gtp#219]
Dear Devs,

This tool has great potential, especially the kernel GTP feature makes it really nice for load generation tests.

Only problem is that the S1AP interface is implemented on top of TCP, while S1AP requires SCTP transport. Therefor this tool cannot attach to any live network nodes (or other open source core projects), as everybody uses SCTP for S1AP transport. In fact pretty much all core signalling interfaces are using SCTP, the only known exception is DIAMETER where TCP is allowed (although pretty much everybody uses SCTP here as well).

Is there a plan to use SCTP instead of TCP? As in this state the tool can only connect to "itself".

**Comment by wmnsk** [comment]
I guess you're talking about gw-tester, correct?
As the document describes, it is to test S/P-GW by mocking eNB and MME, and it's not even using the real S1AP protocol.

**Comment by wmnsk** [comment]
You can find the architecture and concept here: https://github.com/wmnsk/go-gtp/blob/67eb9f0d4a98d07f80bc5cd7a8212f407c06b04b/examples/gw-tester/README.md

**Comment by dchard** [comment]
@wmnsk 

` guess you're talking about gw-tester, correct?`

Correct, the eNB part to be precise.

` it's not even using the real S1AP protocol`

That is the issue: if I give the IP of my MME to the eNB application, it tries to connect via TCP port 36412 instead of SCTP 36412. But I think I get your point: I need to use the eNB app together with MME app (I can see the "fake S1AP" mark on the drawing, I assume you refer to that). Too bad, as quite a lot of implementations lacks the S11 interface, so I cannot use this tool at all.

It would be very nice if the eNB app can work standalone, and would implement at least a basic S1AP via SCTP so the tool can attach to any MMEs. There is an other open source emulator that can do that but rather slow due to the lack of kernel GTP. This project has kernel GTP but cannot work standalone. :-)

**Comment by dchard** [comment]
@wmnsk you used a "confused" emoji on my previous comment.

Just to clear things up: the issue is that most opensource (or commercial enterprise) core solutions does not have an S11 interface implemented (or exposed), and your tool needs an S11 interface from the network under test to be available.

If you can implement basic S1AP signalling into the eNB app, then it can work standalone, no need for the MME part, and that would really widen the ability to use this tool for many more people.

**Comment by wmnsk** [comment]
This is GTP protocol library for Go after all. Thanks for proposal on the tool, but it is just to show a example usage and it’s very unlikely that I would work on implementing a totally different protocol as a part of it (and I don’t have any plan to release go-s1ap). Please try on your own or find something else.
