### ISSUE TITLE
Question on Kernel GTPv1 + UPF

### ISSUE THREAD

**Issue by linouxis9** [wmnsk/go-gtp#228]
Hello,

I'm using your library and I am successfully able to tunnel traffic to a 5G UPF using its userland GTPv1-U features.
However, I'm having trouble using the Linux Kernel GTPv1 feature. I'm receiving no traffic on the interface gtp0 and everything is still routed through userland / uConn.ReadFromGTP as if the TEID was unknown / if the AddTunnel had not been done.

Do you confirm that the following usage of the function AddTunnelOverride is correct?
```go
   if err := uConn.AddTunnelOverride(
    	UPF IP?
    	IP address allocated to UE from SMF?
    	UpLink TEID?
    	DownLink TEID?
    ); err != nil {
        ...
    }
```

Following previous function call and using gtp-tunnel, I'm able to observe the following GTPv1 tunnel created:
```bash
# ./gtp-tunnel list
version 1 tei $DOWNLINK_TEID/$UPLINK_TEID ms_addr $ALLOCATED_UE_IP sgsn_addr $UPF_IP
# ip addr add $ALLOCATED_UE_IP dev gtp0
# ip a
40: gtp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/none 
    inet $ALLOCATED_UE_IP brd X.X.X.255 scope global gtp0
       valid_lft forever preferred_lft forever
```

tcpdump trace of a ping received through the UPF, but no reply:
```bash
15:29:12.331767 IP $UPF_IP.2152 > me.2152: UDP, length 100
15:29:13.353084 IP $UPF_IP.2152 > me.2152: UDP, length 100
```

Do you have any idea on what could be wrong?
Thank you so much!

**Comment by wmnsk** [comment]
Did you call `EnableKernelGTP`? https://pkg.go.dev/github.com/wmnsk/go-gtp/gtpv1#UPlaneConn.EnableKernelGTP

**Comment by wmnsk** [comment]
sounds like it. could you try with it again? https://github.com/wmnsk/go-gtp/tree/master/gtpv1#using-linux-kernel-gtp-u

Also please note that the kernel GTP doesn't fully support 5G - you might need this https://github.com/free5gc/gtp5g or something else, but at least you should see something in the tunnel device/kernel logs if it's correctly set up.

**Comment by linouxis9** [comment]
I'll try and keep you updated, thanks! Thank you for the pointer to gtp5g kernel module as well!

**Comment by linouxis9** [comment]
I was able to do traffic using free5gc's gtp5g module.
However, I was unable to make it work using Linux native GTPv1 module even when running the additional ip commands, as you said this might be linked to incompatibilities with 5G.
Thank you for your help and the pointer to gtp5g!
