### ISSUE TITLE
Compatibility with Windows

### ISSUE THREAD

**Issue by wmnsk** [wmnsk/go-gtp#55]
Since #34 is merged, this project cannot be built on Windows, but it should be supported by isolating platform-specific codes.

As I think there are few people trying to run GTP nodes on Windows, I'm taking this issue as low priority at this moment.

**Comment by gordeyg** [comment]
I'm one of those lucky Windows users. Pretty painful to debug using traces only.
I execute solution through WSL, but debugger does not work with it.
