### ISSUE TITLE
Built-in Metrics support

### ISSUE THREAD

**Issue by krsna1729** [wmnsk/go-gtp#65]
Wondering if metrics #64 should be added to conn/sess itself? Of course it should be optional.

annotated with type/raddr/TEID/bearer/IMSI/TAI labels where possible

1. Counters for message received/sent (already done in #64 with type/raddr labels)
2. Histogram for time spent in system

**Comment by wmnsk** [comment]
Thank you for your idea! 😃
I'd like to consider that carefully from these two points;

1. I don't think it's not so common to implement Prometheus directly into the package itself (not the app). It might not be happy to have an additional dependency for those who are not interested in that.
2. Even if we decide to implement it, labeling with TEID/bearer/IMSI/TAI is not a good practice according to the Prometheus doc, as it can easily be excessive from the cardinality point of view.
https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels

So, my opinion is just to add the methods that are helpful for instrumentation(like `(*Conn).SessionCount()` which is already available). Please tell me what you think.

**Comment by krsna1729** [comment]
Yes makes sense to give all the methods that will be helpful to gather the necessary information to annotate or measure.
