### ISSUE TITLE
Test end-to-end ping/curl following attach/modify/delete

### ISSUE THREAD

**Issue by krsna1729** [wmnsk/go-gtp#70]
To prevent #68 in future we should provide convenience script to use the gw-tester code and test end-to-end connectivity in CI or by developer.

**Comment by wmnsk** [comment]
Agreed.
Since I think the [works by CNF Testbed team](https://github.com/cncf/cnf-testbed/tree/go-gtp) helps it, I'll try that after their use-case is merged into CNF Testbed repo.

**Comment by wmnsk** [comment]
Comment on #81 by @krsna1729 

> If we can have a docker compose file that would bring up the examples (not sure how with gw-tester as they have their own go.mod) and test e2e it would really improve the confidence. Also github actions supports docker-compose. we could upload the packet capture as an artifact too. #70

**Comment by electrocucaracha** [comment]
Hey @wmnsk, I've created a [project](https://github.com/electrocucaracha/gw-tester/) to compare different CNI multiplexer technologies, like [Multus](https://github.com/intel/multus-cni) and [DANM](https://github.com/nokia/danm). Initially I based the development of this using the [CNF Testbed](https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/gogtp-k8s) implementation but at the end I decided to use a different approach to cover End to End provisioning process.

As you can see, I have included two deployment options in this project:

1. **Docker:** This option uses [docker-compose](https://github.com/electrocucaracha/gw-tester/tree/master/docker) to create networks and services required for connecting client with the HTTP server. This project uses [Vagrant](https://www.vagrantup.com/) to provision a VM in VirtualBox or Libvirt. Once you get the source code and installs [vagrant](https://github.com/electrocucaracha/bootstrap-vagrant) you can run the following instruction:
`vagrant up`
2. **Kubernetes:** This option uses [KinD](https://kind.sigs.k8s.io/) tool for deploying a K8s cluster and their required flannel networks . It has to CNI options *Multus* and *DANM*.
`DEPLOY=k8s CNI=danm vagrant up`

I started working on the [Network Service Mesh](https://networkservicemesh.io/) implementation but I noticed that I need to separate Control and User planes. They have dummy 4G example [here](https://github.com/networkservicemesh/examples/blob/master/examples/4g-network/README.md). But when I split P-GW Control from Data plane instructions I faced with [this reference ](https://github.com/wmnsk/go-gtp/blob/master/examples/gw-tester/pgw/handlers.go#L152)in the _handleCreateSessionRequest_ function. I'm not a networking expert but AFAIU I need to communicate those services via PFCP isn't it? Do you have an example on how to achieve this using your go [implementation](https://github.com/wmnsk/go-pfcp)?

BTW: Great work!!!

**Comment by wmnsk** [comment]
Hi @electrocucaracha,

Thank you for working on making it cloud-native. It seems it will help me a lot 😃
As you see, the spec-compliant implementation of CUPS(Control and User Plane Separation) requires the PFCP protocol that is defined in TS 29.244. Unfortunately, however, our [go-pfcp](https://github.com/wmnsk/go-pfcp) project is still in the early stage of development; it does not provide any networking features nor functional examples at this moment, and I cannot share any planning for the future of that project.

**Comment by wmnsk** [comment]
FYI #174 partially resolved this.
