### ISSUE TITLE
Fork friendly go mod

### ISSUE THREAD

**Issue by krsna1729** [wmnsk/go-gtp#78]
Should we rename the module to be go-gtp instead of the github url and appropriately change the import path? Would this make it more fork friendly? I did face an issue when trying to build my app using forked copy. I could only build with local copy and not pointing to my github using the replace keyword

**Comment by wmnsk** [comment]
Mmm I think I don’t fully understand what you pointed out... Doesn’t replace keyword work? That’s weird but I have no idea what causes that.

**Comment by krsna1729** [comment]
Closing this as this seems to be working. Not sure what I did wrong earlier.
