### ISSUE TITLE
Rename package names

### ISSUE THREAD

**Issue by wmnsk** [wmnsk/go-gtp#83]
The names of the package is somewhat confusing. At some point before tagging v1.0.0, I’ll change the names as follows.

v0, v1, v2 => gtpv0, gtpv1, gtpv2
messages => message
ies => ie

**Comment by gordeyg** [comment]
Do you plan to change it only short before 1.0.0 ? 
How will you react if if you will see this kind of PR in near future? 

(just asking yet! Cause I got into the same trap  thinking  "wait, there is v2 of go-gtp?" )

**Comment by wmnsk** [comment]
I has been kept in my mind and is left as it is for long because I don’t **currently** have big motivation to update it.
So, when I get aPR that covers this, it’s nothing but nice for me 😉
