### ISSUE TITLE
c.MarshalLen() and c.Header.MarshalLen() return the same value

### ISSUE THREAD

**Issue by oicnysa** [wmnsk/go-gtp#90]
Hi, I'm trying to Marshal my CreatePDPContextRequest back to binary, but got following error for IMSI IE:
`too short to serialize`

First I was receiving bytes and parsing them like this:
`createPDPContReq, err := gtp_messages_v1.ParseCreatePDPContextRequest(gtpPacket)`
I've changed some values:
`createPDPContReq.SGSNAddressForSignalling = ies_v1.NewGSNAddress(gtpcAddress)
 createPDPContReq.SGSNAddressForSignalling.SetLength()
 createPDPContReq.SGSNAddressForUserTraffic = ies_v1.NewGSNAddress(gtpuAddress)
 createPDPContReq.SGSNAddressForUserTraffic.SetLength()
 createPDPContReq.TEIDDataI = ies_v1.NewTEIDDataI(downlinkTeidProxyGGSN)`

Finally I wanted to Marshal this request back to binary and send it:
`createPDPContReqBytes, err := createPDPContReq.Marshal()`

But, I see that in:
`func (c *CreatePDPContextRequest) MarshalTo(b []byte) error {`

there is line, where we are making header payload:
`c.Header.Payload = make([]byte, c.MarshalLen()-c.Header.MarshalLen())`

But  c.MarshalLen() and c.Header.MarshalLen() return the same value, so c.Header.Payload will be equal to 0.
Could you please advice? :)

**Comment by wmnsk** [comment]
What if `SetLength()` is called before `Marshal()`?

**Comment by oicnysa** [comment]
Well actually SetLength() is called before Marashal(). But anyway, if I comment out those lines and only try to Unmarashal/Marshal createPdpContextReq, it will fail with `too short to serialize message`

**Comment by oicnysa** [comment]
I've tried, but it didn't help.

**Comment by oicnysa** [comment]
I guess, I need to do `createPDPContReq.Payload = nil` before marashling

**Comment by wmnsk** [comment]
Then please try that tell me the result?

**Comment by oicnysa** [comment]
After adding `createPDPContReq.Payload = nil` before marshaling, everything went fine. So I'm closing the issue.
